### ISSUE TITLE
Fix various package's invalid icons

### ISSUE THREAD

**Issue by tobilg** [mesosphere/universe#1001]
There are multiple packages which currently have invalid/missing images:

* dcos-enterprise-cli
* dynatrace
* sysdig-cloud
* tunnel-cli
* vamp

Some have mixed content warning, because they're only served via HTTP, and not HTTPS. Others are just missing. Goal should be that all images/icons are served via HTTPS and are available.

**Comment by tobilg** [comment]
The `spark-history` package has no icons at all. Can this be fixed as well @mgummelt?

**Comment by tobilg** [comment]
Any news here, @ryadav88?

**Comment by Rohithzr** [comment]
@tobilg i think i will make a PR for this issue, i actually face the same issue.

so i can see i would need to simply fix the images in the `resource.json` specifically the `images` object. but do I also change the version in package.json ?

please let me know the actions ahead.

thanks

**Comment by Rohithzr** [comment]
@tobilg i also find an issue where some https images are not available. and they do are on custom domains... i can host them somewhere (like firebase, for free) but i need your opinion on this. what is the correct practice

**Comment by Rohithzr** [comment]
images not available for following packages

- [Riak](https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/R/riak/1/resource.json#L5)
- [Mysql Small Image](https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/M/mysql/4/resource.json#L3)

https images not available for following packages (http is available)

- [sysdigcloud](https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/S/sysdigcloud/0/resource.json#L10)
-

**Comment by Rohithzr** [comment]
@tobilg can you check this commit? most things are fixed https://github.com/Rohithzr/universe/commit/7e872d175c0ac6cd81335c4eac51d6a7e0fe156d

**Comment by tobilg** [comment]
@ryadav88 Can you please have a look? Thanks.

**Comment by tobilg** [comment]
Currently, [universe.dcos.io](http://universe.dcos.io/#/packages) only shows the `spark-history` package with a broken images
