### ISSUE TITLE
How to change package.json 's description to newline ? 

### ISSUE THREAD

**Issue by gl328518397** [mesosphere/universe#1017]
my  package.json  is just like 
 "description": "key1: value1; key2: value2; key3: value3. ",

I want see It in GUI like

Description
key1 value1;
key2: value2;
key3: value3.

How can I edit the package.json file?

**Comment by cruhland** [comment]
The JSON spec allows newlines in strings, as long as they are properly escaped (`\n`); see https://tools.ietf.org/html/rfc7159#section-7. I'm not sure how well the DC/OS GUI or CLI will handle them, however. cc @tamarrow @rcorral

**Comment by gl328518397** [comment]
@cruhland  Hi ,thank you ,I have try and It dones't work.

**Comment by gl328518397** [comment]
@cruhland  Hi I fix it by add  "\n\n" .
