### ISSUE TITLE
Tensorflow

### ISSUE THREAD

**Issue by bhack** [mesosphere/universe#1026]
As TF has more than 50k stargazers it is important to try to figure out how to support this popular framework in universe.
See also https://github.com/tensorflow/ecosystem/issues/25#issuecomment-286879391

**Comment by bhack** [comment]
And also TF serving https://github.com/tensorflow/serving

**Comment by deric** [comment]
Tensorflow is currently in [beta](https://github.com/mesosphere/universe/tree/version-3.x/repo/packages/B/beta-tensorflow/0). See [Kevin's blog post](https://mesosphere.com/blog/tensorflow-gpu-support-deep-learning/) for more details or watch the [announcement from MesosCon Europe](https://www.youtube.com/watch?v=vsyU9R3y7VA&list=PLbzoR-pLrL6rSBqPhTh_lmeMmxn6AOSjf&index=22).
