### ISSUE TITLE
beta-hdfs service failed to install

### ISSUE THREAD

**Issue by yuchaoran2011** [mesosphere/universe#1149]
I'm unable to install beta-hdfs from the universe. hdfs package works fine though. The error I got was "Options JSON validation failed". Screenshot attached.
<img width="402" alt="screen shot 2017-05-04 at 6 40 08 pm" src="https://cloud.githubusercontent.com/assets/1168769/25727803/45bc4b18-30f9-11e7-8032-1b206c930a38.png">
This happens to both 1.3.1-2.6.0-cdh5.9.1-beta (the latest) and 1.3.0-2.6.0-cdh5.9.1-beta.
./scripts/build.sh verified all the json's in the repo/ folder and no error was reported.

**Comment by joerg84** [comment]
@yuchaoran2011 you have to go in Advanced Installation and check the "Agree to beta terms" box.
<img width="791" alt="screen shot 2017-05-26 at 11 17 17" src="https://cloud.githubusercontent.com/assets/10809446/26478115/f5f6a0fc-4204-11e7-833f-381599a40183.png">

**Comment by yuchaoran2011** [comment]
@joerg84 Thanks!
