### ISSUE TITLE
flink package fails to start after restart

### ISSUE THREAD

**Issue by wenlock** [mesosphere/universe#1171]
Hi, I'm trying to deploy flink on DC/OS OSS version 1.9 into a small local virtualbox cluster.   After deploying it the first time, it comes up fine, with web interface, but if I put the computer to sleep to work on it later.  When I come back flink doesn't seem to want to come back up.

Looking for guidance on finding the flink package maintainer and possibly how I might go about troubleshooting the issue.   Here is snippet of the log when it's having problems:
https://gist.github.com/wenlock/ddeeebec555a9c7b830cb32ce1b29b73

Message in the log is repeated.

# workaround

Undeploy flink package, and re-deploy it has been my only workaround.

**Comment by joerg84** [comment]
@wenlock Thx for reporting! Will looks into it.

**Comment by wenlock** [comment]
@joerg84 I can't seem to keep my task manager up and running now... Even on clean deploys.  Any tips on how to troubleshoot that?

**Comment by wenlock** [comment]
@joerg84 the flink package is working great for me for last two days now.  I don't seem to be able to reproduce the issues i was seeing 8 days or so ago.  I'll close this issue for now, since i can't reproduce it with more details.
