### ISSUE TITLE
Typo in etcd health check

### ISSUE THREAD

**Issue by deric** [mesosphere/universe#1543]
I'm not an etcd expert but there seems to be a typo in [etcd health check](https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/E/etcd/1/marathon.json.mustache#L32):
```
"path": "/healthz",
```
@jdef James could you have a look at that?

**Comment by jdef** [comment]
https://github.com/mesosphere/etcd-mesos/blob/8208cfad1d876bdd73162dbc7993eb2083ffd0b5/scheduler/scheduler.go#L1040

/healthz should be a valid endpoint. is the health check not working for
you?

**Comment by deric** [comment]
Right, sorry I was looking into etcd source code instead:

https://github.com/coreos/etcd/blob/0dbcd7c1a7321f0fffa4c807d35cd5ca5ed04a00/etcdserver/api/etcdhttp/metrics.go#L51
