### ISSUE TITLE
Add an object to the package metadata to describe images.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/universe#16]
For example, 

```json
{
  "images": {
    "icon-small": "http://some.org/foo/small.png",
    "icon-medium": "http://some.org/foo/medium.png",
    "icon-large": "http://some.org/foo/large.png",
    "screenshots": [
      "http://some.org/foo/screen-1.png",
      "http://some.org/foo/screen-2.png",
      "http://some.org/foo/screen-3.png"
    ]
  }
}
```

We also should add size and format recommendations as non-normative elements of the spec.

**Comment by ConnorDoyle** [comment]
cc @ashenden

**Comment by ashenden** [comment]
Wooo!  Thanks for adding this.  For now, can we start with these fields?

* icon-small
* icon-medium
* icon-large
* screenshot (can we make this an optional array of zero to n screenshots?)

**Comment by ConnorDoyle** [comment]
Sure.  If we want to tighten this up we can specify the raster dimensions of each image type.  We can also specify supported image formats (for example PNG or JPG).  Could you give some guidance on that here?

**Comment by ashenden** [comment]
Let's stick with PNG and JPG for now.

As for the dimensions, these may change.  If I give you something to start with, can we change them later?

**Comment by ConnorDoyle** [comment]
Updated the example JSON snippet with your suggested values.

**Comment by ConnorDoyle** [comment]
Yes, we can surely change them later.  I've started in on a more formal spec of the registry contents, so we can use words like SHOULD (instead of MUST) for aspects that are simply suggestions.  We should deep in mind that many packages will be community-contributed and we don't want to make things too restrictive.

**Comment by ashenden** [comment]
True.  So, let's roll with these for now (forgive the formatting if it's off)...

```javascript
{
  "images": {
    "icons": {
      "small": {
        "width": 48,
        "height": 48,
        "src": "http://some.org/foo/screen-1.png"
      },
      "medium": {
        "width": 128,
        "height": 128,
        "src": "http://some.org/foo/screen-1.png"
      },
      "large": {
        "width": 256,
        "height": 256,
        "src": "http://some.org/foo/screen-1.png"
      }
    },
    "screenshots": [
      "http://some.org/foo/screen-1.png",
      "http://some.org/foo/screen-2.png",
      "http://some.org/foo/screen-3.png"
    ]
  }
}
```

**Comment by ConnorDoyle** [comment]
Thanks John!  I'll turn these into recommendations in the spec.  Probably no need to encode these in each package JSON.

Also, I'm guessing you've seen the iOS human interface guidelines but I just found a section on icons for mobile.  Could be helpful as a reference: https://developer.apple.com/library/ios/documentation/UserExperience/Conceptual/MobileHIG/IconMatrix.html.
