### ISSUE TITLE
The provided scripts generate invalid json schema

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/universe#169]
I have following installation:
python 2.7.9
jsonschema 2.5.1

If I build the package with the script provided `./scripts/build.sh`, an invalid json is generated.
The first entry of the packages looks like this:
```json
{
  "packages":[
    {
      "versions":{}
    },
```

What am I doing wrong?

**Comment by jsancio** [comment]
@aquamatthias What branch are you running this against?

**Comment by aquamatthias** [comment]
Branch is version-1.x

**Comment by tamarrow** [comment]
Have you tried building this recently? I just tried and it worked for me :/

**Comment by aquamatthias** [comment]
Clean checkout resolved the problem. Closing this ticket.
