### ISSUE TITLE
Kafka Package fails health check

### ISSUE THREAD

**Issue by john-dodson** [mesosphere/universe#172]
After running dcos package install kafka, the Marathon healthcheck just hangs until it times out and fails the task, never getting the kafka service out of a deploying state. When I SSH onto the slave running the process, curling the port that kafka is running on at the /health location times out.

**Comment by john-dodson** [comment]
This is specific to using different instance types than the DCOS standard m3.xlarge. There is already a fix in the kafka-mesos master. A new jar just needs to be built and uploaded to Cloudfront and the DCOS package needs to be updated accordingly.

**Comment by ssk2** [comment]
@john-dodson - looks like the Kafka package was updated a month ago and includes the 0.9.2.0 release of kafka-mesos. I'm hopeful that the new package resolves this problem - please re-open this issue if that is not the case. Thanks!
