### ISSUE TITLE
Confluent control center: typo in environment variable

### ISSUE THREAD

**Issue by dirkjonker** [mesosphere/universe#1760]
See: https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/C/confluent-control-center/10/marathon.json.mustache#L24

On line 24 of the marathon template, for the environment variable `CONTROL-CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS` there is a dash between `CONTROL` and `CENTER` where an underscore should be used.

**Comment by rishabh96b** [comment]
Thanks @dirkjonker!
This issue was fixed in later releases.
