### ISSUE TITLE
Kafka broker param defaults aren't great

### ISSUE THREAD

**Issue by brndnmtthws** [mesosphere/universe#205]
At the moment, the default Kafka broker params are less than ideal. For example, the default number of partitions is 1 (which isn't very intuitive). It would be great if there was a way (through DCOS) to specify more appropriate defaults, or even just change the defaults. For example, the number of partitions should be a nice number like 12, 24, or 48.

In the meantime, I created my own package with the server config and my preferred defaults.

cc @joestein

**Comment by ssk2** [comment]
@brndnmtthws - is this still an issue? It looks like no brokers are started by default currently and the user can manually add brokers via the CLI. If you'd like the CLI to have better defaults, perhaps we could raise an issue against https://github.com/mesosphere/dcos-kafka.

**Comment by brndnmtthws** [comment]
I guess it's pretty easy to change via the CLI, so let's leave the defaults as-is.
