### ISSUE TITLE
pre-commit hook not working?

### ISSUE THREAD

**Issue by casusbelli** [mesosphere/universe#216]
Hi!
Is the pre-commit hook working for anyone?

My issue is that the pre-commit hook sets _UNIVERSE_DIR=$GIT_HOOKS_DIR/.._ but this is not correct as the dir structure is _universe/.git/hooks_ . Thus _UNIVERSE_DIR_ is set to _universe/.git_ and all subsequent script calls fail because _UNIVERSE_DIR/scripts_ cannot be  found (since bash is looking for the non-existing _universe/.git/.scripts_ dir).

I'm looking into the simplest way to fix this.
Looks like updating to _UNIVERSE_DIR=$GIT_HOOKS_DIR/../.._ does the trick.

**Comment by ssk2** [comment]
@casusbelli - looks like [this commit](https://github.com/mesosphere/universe/commit/3ffc687682b0e6dc3fcf68de6e0114a7f69948c7) fixed it. Thanks for raising an issue!
