### ISSUE TITLE
Elasticsearch fails to install with Unknown Option -zk

### ISSUE THREAD

**Issue by jgarcia-mesosphere** [mesosphere/universe#222]
When using `dcos package install elasticsearch`, it fails with the error 
```/bin/sh -c exit `docker wait mesos-fc4657c0-2589-4d93-8f0f-67ed79bbb945` 
com.beust.jcommander.ParameterException: Unknown option: -zk```

**Comment by enxebre** [comment]
same here, think that the marathon file needs to be updated according to the java process options

**Comment by jsancio** [comment]
ElasticSearch is not a package in this repository any more.
