### ISSUE TITLE
Kibana ui wrong path version 6.6.1

### ISSUE THREAD

**Issue by a-nldisr** [mesosphere/universe#2272]
Installed Kibana 6.6.1 from universe, this installed Kibana. When you click the ```Open in new window``` button next to the service it opens to url: 
```https://mydcosurl.com/service/kibana/service/kibana/app/kibana```

When you change the url manually to ```https://mydcosurl.com/service/kibana/app/kibana``` you end up in the right location

**Comment by kaiwalyajoshi** [comment]
@rishabh96b is this fixed by #2527?

**Comment by rishabh96b** [comment]
Yes, we can close this issue now.
