### ISSUE TITLE
Datastax DSE and OpsCenter images point to a bucket that doesn't exist

### ISSUE THREAD

**Issue by wjglerum** [mesosphere/universe#2301]
The images used to display the icons for datastax-dse and datastax-ops in the DC/OS UI are pointing to a bucket that doesn't exists. 

For example:
- DSE: https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/D/datastax-dse/500/resource.json#L16-L20
- OpsCenter: https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/D/datastax-ops/500/resource.json#L16-L20

**Comment by vibhujain** [comment]
Thanks for pointing that out @wjglerum
WIP PR: https://github.com/mesosphere/universe/pull/2321
