### ISSUE TITLE
memsql and mesos authentication: docker container missing libsasl2-modules

### ISSUE THREAD

**Issue by ryane** [mesosphere/universe#237]
The memsql package does not work when mesos authentication is turned on.  Even if you enable authentication with a valid principal and secret using an options file, it will fail with an error like:

```
Failed to authenticate with master master@10.0.218.227:15050: Failed to start the SASL client: SASL(-4): no mechanism available: No worthy mechs found
```

The solution is to install the `libsasl2-modules` package in the Docker image. I was able to build a new image with:

```
FROM memsql/mesos-scheduler
RUN apt-get -y install libsasl2-modules
```

After tweaking the marathon.json to use my image, the memsql framework was able to start up successfully with mesos authentication enabled. 

I'm not sure this is the right place for this issue. It does not appear that the `memsql/mesos-scheduler` docker image is open source - at least nowhere that I could find. I did send the same issue through memsql's bug tracker. But, if there is another place I should open this issue, please let me know where.

**Comment by wsong** [comment]
Hey, I'm from MemSQL and helped write the memsql framework.  Thanks for catching and diagnosing this issue!  We'll push out an updated Docker image soon.

**Comment by wsong** [comment]
I've pushed out an updated mesos-scheduler image with the libsasl2-modules package installed.  Give it a shot and feel free to close this issue if it works.

**Comment by ryane** [comment]
Thanks! Works fine with the updated image. Closing.
