### ISSUE TITLE
Marathon package should construct zk url using marathon.zk and marathon.framework-name

### ISSUE THREAD

**Issue by jsancio** [mesosphere/universe#252]
To guarantee that the Marathon zk node is unique we should construct the url as follow: `--zk {{marathon.zk}}/{{marathon.framework-name}}`. We were doing this in revision 2 of the package but was changed when we moved to revision 3. Does anyone remember why?

cc @kolloch @aquamatthias

**Comment by ssk2** [comment]
@jsancio - it looks like this might be a bug. @aquamatthias is working on a tool to generate Marathon DCOS app configs and we can re-assess this with that.

**Comment by jgarcia-mesosphere** [comment]
Sorry team, just couldn't bear to wait: https://github.com/mesosphere/universe/pull/273

**Comment by aquamatthias** [comment]
This is fixed in #268

**Comment by jgarcia-mesosphere** [comment]
#268 is not yet available, and users are reporting issues while trying to follow the official docs. We need to merge this to make it work until #268 is available.

**Comment by jsancio** [comment]
I just did an install of marathon in `version-2.x` and by default it took over the `universe` znode. It should do that ideally by default is should use `universe/marathon-user`

cc @aquamatthias

**Comment by aquamatthias** [comment]
@jsancio what is the story about version 2? When will it be the default? We currently only maintain version 1.

**Comment by aquamatthias** [comment]
As far as I see you created version 2

**Comment by jsancio** [comment]
@aquamatthias version-2.x will become the default after 1.6.1 (when we release Cosmos). I created version-2.x for Marathon for you. I did this by copying the latest Marathon package and refactoring it to conform to the version-2.x spec.

**Comment by jsancio** [comment]
Assigning back to you. Let me know if you need anything from me.

**Comment by aquamatthias** [comment]
So what is the schedule for 1.6.1?
