### ISSUE TITLE
400 on trying to download local-universe.tar.gz

### ISSUE THREAD

**Issue by a-nldisr** [mesosphere/universe#2591]
https://github.com/mesosphere/universe/blob/version-3.x/docker/local-universe/README.md
The URL's to mesosphere domain in this link are outdated. example: https://downloads.mesosphere.com/universe/public/local-universe.tar.gz 404

**Comment by pierrebeitz** [comment]
file is present. likely a permission issue. 🤔 
@fatz?

**Comment by fatz** [comment]
No i guess the file is to big. We had such issues already. The max cloudfront filesize is 20G this file is about 28G

I just checked the docs we don't seem to have local universe somewhere in our docs anymore!? There is a way which we provide to EE customers. So I'd ask you to contact our support, so you will get a working universe address from them.

@pierrebeitz we should take this into the next DC/OS meeting. The here mentioned README is outdated and we must decide how to rephrase this and provide a different solution
