### ISSUE TITLE
Change file name of marathon template

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/universe#27]
It's conventional for mustache-templated files to be named with a `.mustache` suffix.  Consider changing the name of the marathon template to `marathon.json.mustache`.

**Comment by jsancio** [comment]
Do you mean `marathon.json.mustache` instead of `marathon.json.template`?

**Comment by ConnorDoyle** [comment]
Yes.

**Comment by ssk2** [comment]
Is this still a desirable change? We don't use `marathon.json.template` anymore.

**Comment by jsancio** [comment]
This is done.
