### ISSUE TITLE
Git pre-commit hook enforces an old Marathon version

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/universe#301]
After committing an update to the universe, I noticed that the current Marathon version was automatically set to 0.13.0 instead of the correct 0.15.2. 

The issue seems to be [this call to `sorted`](https://github.com/mesosphere/universe/blob/version-1.x/scripts/build-index.py#L65), which sorts on string rather than int values.

**Comment by BenWhitehead** [comment]
`version-1.x` branch is deprecated. This issue doesn't affect `version-2.x` or `version-3.x`
