### ISSUE TITLE
openvpn-admin package has DCOS_PACKAGE_FRAMEWORK_NAME label

### ISSUE THREAD

**Issue by rcorral** [mesosphere/universe#371]
When the `openvpn-admin` package registers with Marathon, it has the `DCOS_PACKAGE_FRAMEWORK_NAME` and it shouldn't.

**Comment by jsancio** [comment]
@pyronicide are you familiar with the implementation? Can you confirm that openvpn-admin is not a framework?

**Comment by pyronicide** [comment]
It doesn't look like its a framework. Definitely passing that label right now.
