### ISSUE TITLE
It is cumbersome to compile the index every time a package is added or modified

### ISSUE THREAD

**Issue by jsancio** [mesosphere/universe#40]
Having to recompute the index for every package change is not optimal specially when there are multiple pending PR. Or when master changes after merging a PR. Do we need to compute the index every time a package is added? Can this be done on by the client on package update?

@ConnorDoyle @BenWhitehead

**Comment by ConnorDoyle** [comment]
You're right.  Currently rebases are painful.  For background, we wanted the index file to always be up-to-date with the registry contents to allow thin clients to only fetch that file.  One concrete use case is that in the near future we might want to build a web-based frontend for package registries.  Can you guys think of a reasonable way to address this while still ensuring that the index contains accurate and reliable info?

**Comment by ssk2** [comment]
Could the index permanently live on a special git branch in the case of git
repos? It could then be recomputed manually or automatically by a TeamCity
build.

**Comment by ConnorDoyle** [comment]
That could work for us, but it's difficult to express in a spec and significantly raises the bar for hosting your own private universe registry.

**Comment by BenWhitehead** [comment]
Having the index in a git branch makes it challenging to update no matter where it is.

We're probably going to have to create something that can serve an appropriate index based off certain constraints (alpha, beta, GA, etc) if we have a serving abstraction then the index can be built every build and collected as an artifact or uploaded to s3.

**Comment by ssk2** [comment]
The index is built automatically with the pre-commit hook. Assuming this is set up correctly (I'm in the process of adding instructions to the README), the index will get updated with every commit and this should not be an issue anymore. I'm inclined to say this is not too much of an issue anymore but let me know if you disagree.

**Comment by BenWhitehead** [comment]
obsolete in version-3.x branch.
