### ISSUE TITLE
Kubernetes

### ISSUE THREAD

**Issue by bscott** [mesosphere/universe#429]
Is Kubernetes getting added to the repo?

**Comment by air** [comment]
Kubernetes isn't currently installable, it became incompatible with the recent changes in DCOS 1.6.

We aren't working on that package right now, but we'd love some help moving it forward: https://github.com/mesosphere/kubernetes-mesos/milestones

**Comment by bscott** [comment]
@air Thanks, is the plan to get 1.2 supported?

**Comment by air** [comment]
No problem. Our current plan is 100% focused on DC/OS features but I hope we can get back to it eventually.

**Comment by air** [comment]
Let me know if I can help further!
