### ISSUE TITLE
cassandra

### ISSUE THREAD

**Issue by thbeh** [mesosphere/universe#487]
Hi, I have successfully deploy dcos on bare metals (1 master, 1 bootstrap,3 agents). I have also deployed cassandra from bootstrap (using cli) successfully. My problem now is I can't  dcos ssh into cassandra from boostrap server. I have started ssh-agent and use ssh-add to add both bootstrap and master's id_rsa. When I  **_dcos node ssh --master-proxy --leader_** it keep asking for the password (my master is 192.168.20.11). Did I missed anything?

**Running `ssh -A -t core@192.168.20.11 ssh -A -t core@192.168.20.11`
core@192.168.20.11's password:**

my nodes connection -

dcos cassandra connection
{
    "address": [
        "192.168.20.16:9042",
        "192.168.20.15:9042",
        "192.168.20.14:9042"
    ],
    "dns": [
        "node-0.cassandra.mesos:9042",
        "node-1.cassandra.mesos:9042",
        "node-2.cassandra.mesos:9042"
    ]
}

**Comment by triclambert** [comment]
Hi there, is this issue still relevant?  If so, please reopen.  Hope you got it to work!
