### ISSUE TITLE
Issue with registered repositories

### ISSUE THREAD

**Issue by ltagliamonte** [mesosphere/universe#499]
I'm working on integrate sysdigcloud agent in the mesosphere universe.
I followed the guide https://mesosphere.github.io/universe/, all the pre-commit hook went well i was able to commit here:
https://github.com/ltagliamonte/universe/tree/sysdigcloud
Before submitting a PR I want to test it and I did:
```
dcos package repo add Development https://github.com/ltagliamonte/universe/archive/sysdigcloud.zip
```
navigating the universe from the UI i'm getting to following error:
![screen shot 2016-06-21 at 11 05 35](https://cloud.githubusercontent.com/assets/10259338/16240898/1c7b00bc-37a0-11e6-9d8d-6c80c25ba013.png)

Can someone please explain what i'm doing wrong?

**Comment by jsancio** [comment]
Hi @ltagliamonte, we just changed how packages are stored in Universe and how they get synchronized to DC/OS. We also updated the README and GitHub page at https://mesosphere.github.io/universe/.

Do mind reading it again and see if your issue is resolved.

**Comment by ltagliamonte** [comment]
Hi @jsancio i followed the new guide thank you for linking me there, i did some build but is seems that the generated docker containers has some problem:
https://teamcity.mesosphere.io/viewType.html?buildTypeId=Oss_Universe_UniverseServer&branch_Oss_Universe_2=pull%2F500&tab=buildTypeStatusDiv
i can successfully deploy the builds 129,130,136
i can't deploy the builds: 137,144,153
the nginx in container is logging the following error:
```
2016/06/22 21:46:37 [error] 5#5: *1 open() "/etc/nginx/html/repo-empty-v3.json" failed (13: Permission denied), client: 10.1.1.95, server: universe.marathon.mesos, request: "GET /repo-empty-v3.json HTTP/1.1", host: "10.1.1.72:8085"
10.1.1.95 - - [22/Jun/2016:21:46:37 +0000] "GET /repo-empty-v3.json HTTP/1.1" 403 169 "-" "spray-can/1.3.2"
```
Can someone please have a look at the generated container?

**Comment by ltagliamonte** [comment]
it seems fixed with https://github.com/mesosphere/universe/commit/af0d2ca24155aa4408dd00f5bac7ee30b01728a9

**Comment by BenWhitehead** [comment]
Thanks for raising this @ltagliamonte.

The issue ended up being that the image that was built for you, was a different base docker image than the one I had tested with :(

The update I made to fix the issue was to ensure that the files will always be accessible regardless of the inherent permissions in the base image.  Sorry for the issue.
