### ISSUE TITLE
There is no "repo" in http service container

### ISSUE THREAD

**Issue by subodhp** [mesosphere/universe#538]
HI,

I am trying to onboard local-universe on DCOS 1.7.
The http container service starts correctly on the port 8082.
The URL http://master.mesos:8082 works fine.
http://master.mesos:8082/repo doesn't.

It turns out that there is no content named repo in the local-universe container at /usr/share/nginx/html/repo (inside container)

I am not able to install Spark due to this as Repository service is not present.

Please advise.

Thanks,
Subodh Pachghare

**Comment by mnp** [comment]
The /repo endpoint is intercepted by the nginx config file and mapped to one of the JSON or ZIP files in /usr/share/nginx/html.  Note that both User-Agent: and Accept: tags are examined by nginx to make this mapping:
- Accept: clients use this to pass in expected Universe protocol version: v3  for dcos up to 1.9 and v4 for dcos >= 1.10
-  User-Agent: header, which indicates the DCOS version to show repo for.

An example Curl if you're going by hand is:

    curl -H 'Accept: application/vnd.dcos.universe.repo+json;charset=utf-8;version=v3' -A 'dcos/1.8' http://dev-universe.marathon.mesos:8085/repo
