### ISSUE TITLE
config.json should be documented

### ISSUE THREAD

**Issue by mgummelt** [mesosphere/universe#56]
It's unclear what config.json is for, and it seems that at least the "properties" property is required, which is undocumented.  I was only able to continue by creating a dummy config.json.

**Comment by ssk2** [comment]
@mgummelt - is this any clearer now that we have several other example packages?

**Comment by mgummelt** [comment]
I think adding a short description in the `config.json` section would be an improvement.  At least something saying it's a JSON schema object.
