### ISSUE TITLE
Where did the index.json file go from version 2.x to 3.x

### ISSUE THREAD

**Issue by tobilg** [mesosphere/universe#593]
I noticed that the former existing (`2.x`) file `repo/meta/index.json` is gone in `3.x`. Is this by purpose?

If so, is there a replacement, or another mechanism to get the repository contents in one file?

**Comment by jsancio** [comment]
Hi @tobilg, starting with version `3.x` the list of packages is dependent on the version of the DC/OS cluster. The easiest way to get a list packages for your cluster to run the following CLI command against your cluster:

```
dcos package search --json
```

If you don't have a DC/OS cluster you can use HTTP directly. For example:

```
http --follow https://universe.mesosphere.com/repo "accept:application/vnd.dcos.universe.repo+json;charset=utf-8;version=v3" user-agent:dcos/1.8
```

I should point out that this is an internal API and it may change in the future. Please close this issue if that answers your question. Thanks!

**Comment by tobilg** [comment]
Thanks for the info! So basically, there is no longer a single file containing the index of packages, but a web service the CLI and DC/OS can use if I understand correctly?

I tried to do a 

    GET https://universe.mesosphere.com/repo

with the headers you outlined, and received the following error message:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error>
    <Code>AccessDenied</Code>
    <Message>Access Denied</Message>
    <RequestId>B4B5DC2258E45044</RequestId>
    <HostId>gcm13ZKeg6Pdv3XUTFxqo4b96IHijphWZO2VjULu50Hi7KiBwjRJPdQ0DF+/uJk7</HostId>
</Error>
```

**Comment by BenWhitehead** [comment]
You are correct, when a client wants to read from the universe it is no longer read directly from this git repo, instead it is read from a service (either universe-server, or universe.mesosphere.com).

@tobilg ensure that the accept and user-agent headers are sent with your request, they are important. Can you provide the full request you sent when you got the error?

Alternatively you could run the universe-server docker image and test against that (You could build it yourself from this repo, or run one of the tags from docker-hub https://hub.docker.com/r/mesosphere/universe-server/tags/ (there are many tags it can take a minute for docker hub to load))

**Comment by BenWhitehead** [comment]
Actually docker-hub is timing out most of the time, this is the latest tag of universe-server `mesosphere/universe-server:20160729T162808Z-version-3.x-9800c596d5`

**Comment by tobilg** [comment]
Thanks!

Postman gives me this:

```
curl -X GET -H "Content-Type: application/json;charset=utf8" -H "user-agent: dcos/1.8" -H "accept: application/vnd.dcos.universe.repo+json" -H "Cache-Control: no-cache" "https://universe.mesosphere.com/repo"
```
If I use it like this, I can at least get an output, but it contains non-standard characters.

**Comment by BenWhitehead** [comment]
The accept header value has to be exactly 'application/vnd.dcos.universe.repo+json;charset=utf-8;version=v3'. the charset and version are significant, ensure those are there. Otherwise the routing won't work correctly. (The server right now is nginx, so error handling is quite limited).

**Comment by tobilg** [comment]
Using this now:

```
curl -X GET -H "user-agent: dcos/1.8" -H "accept: application/vnd.dcos.universe.repo+json;charset=utf-8;version=v3" "https://universe.mesosphere.com/repo"
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx/1.11.1</center>
</body>
</html>
```

**Comment by BenWhitehead** [comment]
Add `-L` to your curl command so it will follow the redirect.

**Comment by tobilg** [comment]
Thanks, just noticed myself :-/ Sorry!

**Comment by BenWhitehead** [comment]
No worries, glad you got it working.
