### ISSUE TITLE
Create a script for generating the Marathon app definition locally for testing

### ISSUE THREAD

**Issue by tobilg** [mesosphere/universe#685]
I recently added the `marathon-slack` package to the universe, which was also merged (https://github.com/mesosphere/universe/pull/678). Even though the `scripts/build.sh` script didn't show any problems, it turned out that the generated Marathon app definition didn't work, probably because of an issue with Marathon (see https://github.com/mesosphere/marathon/issues/4333).

I would like to suggest to include a script which will ask for a configuration, as well as render and output the application JSON as it would be rendered by the DC/OS UI, which would make it possible to test the application definition locally without necessarily having to build a local universe server. This would probably avoid similar problems like I had.

Or does something like this already exist?

**Comment by BenWhitehead** [comment]
@tobilg The rendering of the template is not something Universe is currently responsible for, the rendering is done by the consumer of the package definition ([cosmos](https://github.com/dcos/cosmos) for example).  And both universe and cosmos do not do any deep validation of the rendered marathon template since the validation logic of the app definition changes very frequently.

**Comment by tobilg** [comment]
Thanks for the fast feedback, @BenWhitehead! I know that Universe is not responsible for the rendering, but as far as I understand the build.sh script actually is validating the JSON schemas, right?

That's why I thought it would maybe ne useful to include this functionality... Is there a suggested way to do a "front-to-back" test when developing new packages? The build.sh only validates the JSON schema, but not the resulting application definition. That's what bit me somehow.

**Comment by BenWhitehead** [comment]
The marathon.json.mustache does not have a schema itself, it is just a bunch of bytes, and can't be verified until rendered.

And the versions of marathon is a moving target crossing multiple versions of dc/os at the same time. Unfortunately the only real way to validate the the template is to render it and install it on all versions of dc/os it claims to be compatible with.

**Comment by tobilg** [comment]
Yes, you're correct in the last paragraph, this would be a lot of manual work... Would there be a chance to integrate this in your TeamCity builds/tests for the Universe somehow? I guess nobody will have all the different DC/OS versions running.

Is there any suggestion on how package creator/maintainers can test their packages in a more complete way? Or, to rephrase it, what it the currently best suggestion? Building and running a custom Universe locally, and connect the local DC/OS to this and trying to install the package?

**Comment by BenWhitehead** [comment]
Integrating it into TeamCity is unlikely to happen. We're in the process of evaluating the process of publishing and package and how we can improve it. We don't have any details yet but hopefully in the near future we will.

The best suggestion at this time, is as you say, build a universe-server (either locally or use one built from a PR) and then install the package on your dc/os cluster, ideally of the same version that `minDcosRelaseVersion` has been set to.

**Comment by tobilg** [comment]
Great, will do as you described. Looking forward to the new process... Thanks again for your time
