### ISSUE TITLE
marathon.json location when building Universe Server

### ISSUE THREAD

**Issue by NimaVaziri** [mesosphere/universe#691]
The [docs](https://github.com/mesosphere/universe#run-universe-server) mention the "`marathon.json` that is created when building Universe Server", but doesn't mention where this file is located.

**Comment by BenWhitehead** [comment]
The location is listed in the section [Build Universe Server Locally](https://github.com/mesosphere/universe#build-universe-server-locally) item 2.

**Comment by NimaVaziri** [comment]
My bad, not sure how I didn't see that. Closing.
