### ISSUE TITLE
Create Universe Package browser

### ISSUE THREAD

**Issue by ryadav88** [mesosphere/universe#775]
a listing of DC/OS packages that is autogenerated from the Universe repo itself. This would allow people to see what packages exist without having to go to the GitHub repo and trawl the JSON file

More info here: https://dcosjira.atlassian.net/browse/SITE-44

**Comment by dluc** [comment]
I agree that would be useful indeed. As the list grows, this will become more and more useful when looking for solutions supported.

**Comment by tobilg** [comment]
I created a Universe package browser, which is available at https://universe.serv.sh

The project / repo behind it can be found at https://github.com/tobilg/dcos-universe-browser 

Please let me know if you have some feedback, positive or negative, both welcome!

**Comment by tobilg** [comment]
Shall this issue be closed? @ryadav88

**Comment by ryadav88** [comment]
Yes
