### ISSUE TITLE
Elasticsearch package is broken

### ISSUE THREAD

**Issue by gisjedi** [mesosphere/universe#789]
Elasticsearch package uses `elasticsearch:latest` docker image for the executors scheduled by the framework.  This is broken as of 10/26/2016 due to latest image migrating to ES 5.0.  The package can be fixed by specifying an explicit default of `elasticsearch:2.3` using --elasticsearchDockerImage argument to the scheduler.

**Comment by ryadav88** [comment]
closing per #790

**Comment by gisjedi** [comment]
This has been broken again as of https://github.com/mesosphere/universe/commit/23a4547b447851cbaeda586ec3827147fd2ede97. I'd recommend changing the default value for `docker-image` in config.json to `elasticsearch:2.3`.

**Comment by ardlema** [comment]
Hi @gisjedi, not fully understand you. Do you mean that the framework does not work with images greater than 2.3? Have you tested it out with 2.4 version?

Anyway with the changes included in the PR that has just been merged you can now define the image you want to use by typing it within the new docker-image parameter

**Comment by ardlema** [comment]
I've just deployed ES in my DC/OS cluster using the 2.4 docker image and it is up & running:

![es24](https://cloud.githubusercontent.com/assets/1173286/20183383/65bda4f2-a765-11e6-8e47-1814247a1855.png)

**Comment by gisjedi** [comment]
@ardlema Thanks for follow-up. The issue is that if you _don't_ change the default, Elasticsearch will fail to start up. The default `elasticsearch:latest`image is incompatible with the JVM Heap arguments that the Elasticsearch scheduler is providing since `latest` now points to 5+. My suggestion was just to update the default so new users don't have to debug why the package fails to start.

I do appreciate the addition of a package config option to specify the elasticsearch image used by the executors, rather than modify the Marathon args manually. Thanks!

**Comment by albertostratio** [comment]
Ok, I've got it @gisjedi. Thank you for clarifying.

In that case I think that it makes a lot of sense to set the default image to the latest that is working fine right now and when the people behind the framework make it compatible with 5+ we'll update the default image to become the latest one again.

If you agree I'll submit a new PR setting the default image to 2.4.1.

**Comment by gisjedi** [comment]
@albertostratio Sounds great! Thanks for the quick turnaround on that.
