### ISSUE TITLE
Add missing descriptions to universe's JSON schema properties

### ISSUE THREAD

**Issue by tobilg** [mesosphere/universe#834]
In the some of the JSON schemas of the Universe, the descriptions of some properties are missing. Examples are:

* https://github.com/mesosphere/universe/blob/version-3.x/repo/meta/schema/package-schema.json#L23-L44
* https://github.com/mesosphere/universe/blob/version-3.x/repo/meta/schema/package-schema.json#L109-L130
* https://github.com/mesosphere/universe/blob/version-3.x/repo/meta/schema/v3-resource-schema.json

I think this would add some clarity for people who want to get started in package development. Thanks!

**Comment by tobilg** [comment]
Any chance this will be fixed @ryadav88 @ssk2? Thanks!

**Comment by ryadav88** [comment]
@jsancio @cruhland ^^

**Comment by cruhland** [comment]
We'll address this next sprint: [DCOS_OSS-678](https://jira.mesosphere.com/browse/DCOS_OSS-678).

**Comment by tobilg** [comment]
Closing because of #1002 Thanks!
