### ISSUE TITLE
Kafka version not updated with the latest package

### ISSUE THREAD

**Issue by albertostratio** [mesosphere/universe#886]
Having a look at the latest version of the confluent platform package it seems like it's been updated to 3.1.1. The Confluent Platform docs states that kafka's version included within this version is 0.10.1.0 whereas the version included in the resource.json of the latest version is still 0.10.0.0: https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/C/confluent-kafka/10/resource.json

**Comment by ryadav88** [comment]
@dbtucker can you chime in? ^^

**Comment by dbtucker** [comment]
I believe you're referring to these assets in resource.json 
                 "scheduler-zip": "https://downloads.mesosphere.com/kafka/assets/1.1.16-0.10.0.0/scheduler.zip",
            "executor-zip": "https://downloads.mesosphere.com/kafka/assets/1.1.16-0.10.0.0/executor.zip",
            "overrider-zip": "https://downloads.mesosphere.com/kafka/assets/1.1.16-0.10.0.0/overrider.zip"

Those do not represent Apache Kafka itself, merely the DC/OS tooling around the core Kafka software.   The Apache Kafka jar files are part of the Confluent asset (in this case our 3.1.1 tarball) which is definitely Kafka 0.10.1

**Comment by albertostratio** [comment]
Thank you for replying @ryadav88  & @dbtucker 

I guess you mean this guy: "kafka_tgz": "https://packages.confluent.io/archive/3.1/confluent-oss-3.1.1-mesos.tgz"

So...to fully understand what's going on in here the tooling artifacts are still in the version 0.10.0.0 and they are compatible with the version 0.10.1?

**Comment by dbtucker** [comment]
Correct ... the tooling artifacts (scheduler, executor, overrider) will support later versions of Kafka.
