### ISSUE TITLE
Release latest kafka 1.1.17-0.10.1.0 in confluent-kafka

### ISSUE THREAD

**Issue by renou** [mesosphere/universe#888]
The latest kafka is release in kafka package but not in confluent-kafka through https://github.com/mesosphere/universe/pull/873. Please make update to confluent-kafka too, thank you!

**Comment by renou** [comment]
@dbtucker Any plan on releasing? :)

**Comment by dbtucker** [comment]
Separate PR just issued.   Thanks for the ping !

**Comment by renou** [comment]
💥  Thank you!
