### ISSUE TITLE
UnicodeDecodeError while running build script in order to create pull request

### ISSUE THREAD

**Issue by chenko47** [mesosphere/universe#889]
I would like to create a pull request with my fork, but after I've forked and cloned the project, I tried to run /scripts/build.sh script (after install jsonschema by pip module) but got this error : 

```
Validating sqlserver...
        Validating revision 0...
                package.json:Traceback (most recent call last):
  File "/universe/scripts/validate-packages.py", line 123, in <module>
    sys.exit(main())
  File "/universe/scripts/validate-packages.py", line 36, in main
    _validate_package(given_package, package_path)
  File "/universe/scripts/validate-packages.py", line 44, in _validate_package
    _validate_revision(given_package, rev, os.path.join(path, rev))
  File "/universe/scripts/validate-packages.py", line 55, in _validate_revision
    package_json = _validate_json(package_json_path, PACKAGE_JSON_SCHEMA)
  File "/universe/scripts/validate-packages.py", line 109, in _validate_json
    data = json.loads(f.read())
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 494: ordinal not in range(128)

```
using python 3.5 
Any suggestions ?

**Comment by ryadav88** [comment]
@jsancio @cruhland ^^

**Comment by cruhland** [comment]
@chenko47 it appears from the traceback that the contents of `repo/packages/S/sqlserver/0/package.json` contain a non-ASCII Unicode character. It's a single [em dash](http://www.fileformat.info/info/unicode/char/2014/index.htm) (`—`) in the following sentence of the `description` field (between `applications` and `which`):

```
As a database server, it is a software product with the primary function of storing and retrieving data as requested by other software applications—which may run either on the same computer or on another computer across a network (including the Internet).
```

However, I'm not sure why this is causing trouble because I'm unable to reproduce the error in Python 3.5.2 on Linux. Possibly your system is configured to use ASCII encoding by default instead of UTF-8?

**Comment by cruhland** [comment]
I've reproduced the issue by explicitly setting the encoding to ASCII when `open()`ing the file. @chenko47 could you update [this line](https://github.com/mesosphere/universe/blob/f9736cd2209aa8fa7949e85b5d3adbe0f0ee2782/scripts/validate-packages.py#L108) to the following, and confirm that it fixes your issue?

```python
        with open(path, encoding='utf-8') as f:
```

I'll create a PR shortly.
