### ISSUE TITLE
Linkerd webui does not work due to absolute links.

### ISSUE THREAD

**Issue by joerg84** [mesosphere/universe#911]
@siggy @pyronicide @ryadav88 
When trying to access the linkerd webui via adminrouter (e.g.,  by klicking "Open Service") in the UI, the UI will be broken.
See Screenshot below.
<img width="694" alt="screen shot 2017-01-16 at 14 53 52" src="https://cloud.githubusercontent.com/assets/10809446/21985566/a79e720a-dbfb-11e6-9854-9921cc7a4c82.png">

The reason for this is that you use absolute links in the linkerd UI (https://github.com/BuoyantIO/linkerd/blob/master/linkerd/admin/src/main/scala/io/buoyant/linkerd/admin/AdminHandler.scala). 

Is there any problem of changing for example 
`            <img alt="Logo" src="/files/images/linkerd-horizontal-white-transbg-vectorized.svg">
`
to 
`            <img alt="Logo" src="files/images/linkerd-horizontal-white-transbg-vectorized.svg">
`? 

Also setting 
```
  "labels": {
    "DCOS_SERVICE_NAME": "linkerd",
    "DCOS_SERVICE_SCHEME": "http",
    "DCOS_SERVICE_PORT_INDEX": "0"
  },

``` for all your tasks can lead due (short) unavailability of the UI after tasks failures. Feel free to ping me to discuss that in detail.

**Comment by siggy** [comment]
Thanks for all the detail @joerg84! This will require a change in linkerd, tracking that work at: https://github.com/BuoyantIO/linkerd/issues/397
