### ISSUE TITLE
local universe build fails

### ISSUE THREAD

**Issue by csmith-work** [mesosphere/universe#922]
Attempting to build a local universe with `make local-universe` fails on line 78 attempting to make the docker_artifacts temp folder.  Stacktrace is below.  The temp folder is already created from line 70.  Renaming the docker_artifacts folder resolves the issue.

> make local-universe
rm -rf certs &&							\
rm -f local-universe.tar.gz || 0
python3 /root/universe/docker/local-universe/../../scripts/local-universe.py			\
	--repository /root/universe/docker/local-universe/../../repo/packages/	\
	--include="marathon-lb,zeppelin" &&							\
docker save -o local-universe.tar mesosphere/universe:latest &&		\
gzip local-universe.tar
Start docker registry.
cd37c01c3a1d5c68b93c8044e5b8c73dbd9e2a4f03eb593669b31ef55c3ce977
Stopping docker registry.
registry
Traceback (most recent call last):
  File "/root/universe/docker/local-universe/../../scripts/local-universe.py", line 333, in <module>
    sys.exit(main())
  File "/root/universe/docker/local-universe/../../scripts/local-universe.py", line 78, in main
    os.makedirs(str(docker_artifacts))
  File "/usr/lib64/python3/os.py", line 241, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/tmp/tmpslp2u9cr/registry'
make: *** [local-universe] Error 1

**Comment by tobilg** [comment]
Apparently the same as https://github.com/mesosphere/universe/issues/907

**Comment by jsancio** [comment]
This should be fixed. Please let me know if you are still seeing this issue.
