### ISSUE TITLE
Local Universe Build Stores Resource URLs Incorrectly

### ISSUE THREAD

**Issue by drewkerrigan** [mesosphere/universe#931]
For packages like https://github.com/mesosphere/universe/blob/version-3.x/repo/packages/D/dcos-enterprise-cli/10/resource.json, all of the cli binaries have the same name (`dcos-enterprise-cli`). When creating a local-universe.tar.gz, this code: https://github.com/mesosphere/universe/blob/version-3.x/scripts/local-universe.py#L292-L302 will grab all of those binaries and put them at the same path in the nginx serve dir (`/usr/share/nginx/html/dcos-enterprise-cli/uris/dcos-enterprise-cli`)

So with each iteration for the darwin / linux / windows versions of that binary, only the last one written will stay, resulting in the package being uninstallable if you aren’t using the OS that happened to get written last.

Symptom:

```
dcos package install --cli dcos-enterprise-cli
The hash for the downloaded subcommand [<darwin hash>] does not match the expected value [<linux hash>]. Aborting...
```

**Comment by ryadav88** [comment]
@jsancio @cruhland ^^

**Comment by jsancio** [comment]
fixed by https://github.com/mesosphere/universe/pull/933
