### ISSUE TITLE
Use of `jsonschema` and `jq` in build scripts brings in extra dependencies for repo consumers

### ISSUE THREAD

**Issue by dannypurcell** [mesosphere/universe#945]
The README section on [Repository Consumption](https://github.com/mesosphere/universe#repository-consumption-1) says one should be able to do
```
scripts/build.sh
DOCKER_TAG="my-package" docker/server/build.bash
```
however, doing so on a fresh centos box seems to require the installation of the following dependencies
* `sudo yum install epel-release`
* `sudo yum install python34`
* `sudo yum install python34-devel`
* `curl -O https://bootstrap.pypa.io/get-pip.py`
* `sudo /usr/bin/python3.4 get-pip.py`
* `pip install jsonschema`
* `sudo yum install jq`

This significantly complicates the process to merely get a usable copy of the universe repo image.

Additionally, since these dependencies are not mentioned in the README, new users currently have to discover them by banging their head against the console and digging around on the internet. This is likely to arouse hate and discontent among enterprise edition users who need to run a local copy of the Universe for security reasons.

Can we fix up this process so it's a bit nicer to the first time user?

**Comment by joerg84** [comment]
@dannypurcell thx for your feedback! looking into this

**Comment by mastermindg** [comment]
**Why has this not been corrected yet?** This is a simple fix. Just detail the dependencies in the README. It's not like people can't install them - it's just a BIG pain that the dependencies are not listed in the README and users need to come to issues to find this.

**Comment by jsancio** [comment]
@dannypurcell and @mastermindg, excuse the delayed response. We are tracking this and should be scheduled to get worked on soon.
