### ISSUE TITLE
'framework' attribute of package.json not documented in README

### ISSUE THREAD

**Issue by air** [mesosphere/universe#99]
We don't mention the `framework:true` attribute in https://github.com/mesosphere/universe/blob/master/README.md#packagejson

We do have the word `framework` as an example of a tag - not sure if related (maybe that was an earlier approach?). Maybe clearer to remove that as a tag example.

It's definitely used in e.g. the HDFS package.json.

**Comment by kensipe** [comment]
all use of the word `framework` has been depreciated.  you will not see any use in `version-2.x` or moving forward.
