### ISSUE TITLE
Request to Bump Neo4j Version

### ISSUE THREAD

**Issue by toddleo** [mesosphere/universe#991]
Hi,

Neo4j has released their latest 3.1.1 version on [docker hub](https://hub.docker.com/_/neo4j/), it may looks like a minor version change however it might has solved a bug I encountered to recently. So pls consider bumping Neo4j to 3.1.1. Thx.

**Comment by unterstein** [comment]
:tada: https://github.com/mesosphere/universe/pull/993

**Comment by unterstein** [comment]
In the meantime 3.1.2 was released and I updated directly to this newer version :)
